/**
 * 国家地图文件映射表
 *
 * @description
 * 将国家名称映射到对应的 GeoJSON 文件名
 *
 * @remarks
 * - 数据来源：country keys 从 world/wgs84_world.geo.json 中提取
 * - 有独立数据文件的国家：值为文件前缀（如 "ca-all" 对应 countries/ca-all.geo.json）
 * - 无独立数据文件的国家：值为 null（包含在 world/wgs84_world.geo.json 中）
 *
 * @example
 * ```ts
 * { "Canada": "ca-all" }   // → countries/ca-all.geo.json
 * { "Brazil": null }       // → 包含在 world/wgs84_world.geo.json 中
 * ```
 */
export default {
  // 有数据文件的国家（按字母顺序排列）
  "Canada": "ca-all",
  "France": "fr-all",
  "Germany": "de-all",
  "India": "in-all",
  "Japan": "jp-all",
  "Korea": "kr-all",
  "Russia": "ru-all",
  "Singapore": "sg-all",
  "United Kingdom": "uk-all",
  "United States": "us-all",
  // 没有数据文件的国家（按字母顺序排列）
  "Afghanistan": null,
  "Albania": null,
  "Algeria": null,
  "American Samoa": null,
  "Andorra": null,
  "Angola": null,
  "Antigua and Barb.": null,
  "Argentina": null,
  "Armenia": null,
  "Austria": null,
  "Azerbaijan": null,
  "Bahamas": null,
  "Bahrain": null,
  "Bangladesh": null,
  "Barbados": null,
  "Belarus": null,
  "Belgium": null,
  "Belize": null,
  "Benin": null,
  "Bhutan": null,
  "Bolivia": null,
  "Bosnia and Herz.": null,
  "Botswana": null,
  "Brazil": null,
  "Brunei": null,
  "Bulgaria": null,
  "Burkina Faso": null,
  "Burundi": null,
  "Cambodia": null,
  "Cameroon": null,
  "Cape Verde": null,
  "Central African Rep.": null,
  "Chad": null,
  "Chile": null,
  "China": null,
  "Colombia": null,
  "Comoros": null,
  "Congo": null,
  "Costa Rica": null,
  "Croatia": null,
  "Cuba": null,
  "Cyprus": null,
  "Czech Rep.": null,
  "Côte d'Ivoire": null,
  "Dem. Rep. Congo": null,
  "Dem. Rep. Korea": null,
  "Denmark": null,
  "Djibouti": null,
  "Dominica": null,
  "Dominican Rep.": null,
  "Ecuador": null,
  "Egypt": null,
  "El Salvador": null,
  "Eq. Guinea": null,
  "Eritrea": null,
  "Estonia": null,
  "Ethiopia": null,
  "Faeroe Is.": null,
  "Fiji": null,
  "Finland": null,
  "Gabon": null,
  "Gambia": null,
  "Georgia": null,
  "Ghana": null,
  "Greece": null,
  "Greenland": null,
  "Grenada": null,
  "Guam": null,
  "Guatemala": null,
  "Guinea": null,
  "Guinea-Bissau": null,
  "Guyana": null,
  "Haiti": null,
  "Honduras": null,
  "Hungary": null,
  "Iceland": null,
  "Indonesia": null,
  "Iran": null,
  "Iraq": null,
  "Ireland": null,
  "Israel": null,
  "Italy": null,
  "Jamaica": null,
  "Jordan": null,
  "Kazakhstan": null,
  "Kenya": null,
  "Kiribati": null,
  "Kosovo": null,
  "Kuwait": null,
  "Kyrgyzstan": null,
  "Lao PDR": null,
  "Latvia": null,
  "Lebanon": null,
  "Lesotho": null,
  "Liberia": null,
  "Libya": null,
  "Liechtenstein": null,
  "Lithuania": null,
  "Luxembourg": null,
  "Macedonia": null,
  "Madagascar": null,
  "Malawi": null,
  "Malaysia": null,
  "Mali": null,
  "Malta": null,
  "Mauritania": null,
  "Mauritius": null,
  "Mexico": null,
  "Moldova": null,
  "Monaco": null,
  "Mongolia": null,
  "Montenegro": null,
  "Morocco": null,
  "Mozambique": null,
  "Myanmar": null,
  "N. Mariana Is.": null,
  "Namibia": null,
  "Nauru": null,
  "Nepal": null,
  "Netherlands": null,
  "New Caledonia": null,
  "New Zealand": null,
  "Nicaragua": null,
  "Niger": null,
  "Nigeria": null,
  "Norway": null,
  "Oman": null,
  "Pakistan": null,
  "Palau": null,
  "Panama": null,
  "Papua New Guinea": null,
  "Paraguay": null,
  "Peru": null,
  "Philippines": null,
  "Poland": null,
  "Portugal": null,
  "Puerto Rico": null,
  "Qatar": null,
  "Romania": null,
  "Rwanda": null,
  "S. Sudan": null,
  "Saint Lucia": null,
  "Samoa": null,
  "San Marino": null,
  "Saudi Arabia": null,
  "Senegal": null,
  "Serbia": null,
  "Seychelles": null,
  "Sierra Leone": null,
  "Sint Maarten": null,
  "Slovakia": null,
  "Slovenia": null,
  "Solomon Is.": null,
  "Somalia": null,
  "South Africa": null,
  "Spain": null,
  "Sri Lanka": null,
  "St. Kitts and Nevis": null,
  "St. Vin. and Gren.": null,
  "Sudan": null,
  "Suriname": null,
  "Swaziland": null,
  "Sweden": null,
  "Switzerland": null,
  "Syria": null,
  "São Tomé and Principe": null,
  "Tajikistan": null,
  "Tanzania": null,
  "Thailand": null,
  "Timor-Leste": null,
  "Togo": null,
  "Trinidad and Tobago": null,
  "Tunisia": null,
  "Turkey": null,
  "Turkmenistan": null,
  "U.S. Virgin Is.": null,
  "Uganda": null,
  "Ukraine": null,
  "United Arab Emirates": null,
  "Uruguay": null,
  "Uzbekistan": null,
  "Vanuatu": null,
  "Venezuela": null,
  "Vietnam": null,
  "W. Sahara": null,
  "Yemen": null,
  "Zambia": null,
  "Zimbabwe": null,
};
